baseURL = "https://ozmoroz.com/"
languageCode = "en-us"
# title = "Sergey Stadnik's blog"
theme = "hugo-theme-bootstrap4-blog"
# number of posts to show on home/category/tag pages (Default: 10)
paginate = 5
# optionally override the site's footer with custom copyright text
copyright = "© 2018 Sergey Stadnik. Powered by [Hugo](https://gohugo.io/), [hugo-theme-bootstrap4-blog](https://github.com/chris-short/hugo-theme-bootstrap4-blog)"
googleAnalytics = "UA-5940328-2"
disqusShortname = "ozmorozcom"

[permalinks]
  post = "/:year/:month/:slug/"
  page = "/:slug/"

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

# [[menu.sidebar]]
#   name = "Link 1"
#   url = "https://ozmoroz.com"

# [[menu.sidebar]]
#   name = "Link 2"
#   url = "https://ozmoroz.com"

# custom navbar menu entry.   See the custom_navbar parameter below for
# details.

[[menu.navbar]]
  name = "About me"
  url = "/about/"
  weight = 1

[[menu.navbar]]
  name = "Now"
  url = "/now/"
  weight = 2

[[menu.navbar]]
  name = "Technology"
  url = "/categories/technology/"
  weight = 3

[[menu.navbar]]
  name = "Lifestyle"
  url = "/categories/lifestyle/"
  weight = 4

# Theme variables
#
[params]
  # Site author
  author = "Sergey Stadnik"
  brand = "Sergey Stadnik" # Site's brand banner

  # Description/subtitle for homepage (can be Markdown)
  # description = "Sergey Stadnik's blog"

  # Format dates with Go's time formatting
  date_format = "Mon Jan 02, 2006"

  # verification string for Google Webmaster Tools
  #google_verify_meta = "BAi57DROASu4b2mkVNA_EyUsobfA7Mq8BmSg7Rn-Zp9"

  # verification string for Bing Webmaster Tools
  #bing_verify_meta = "3DA353059F945D1AA256B1CD8A3DA847"

  # verification string for Yandex Webmaster Tools
  #yandex_verify_meta = "66b077430f35f04a"

  # Optionally display a message about the site's use of cookies, which may be
  # required for your site in the European Union. Set the parameter below to a
  # page where the user can get more information about cookies, either on your
  # site or externally, for example:
  #cookie_consent_info_url = "/cookie-information/"
  #cookie_consent_info_url = "http://cookiesandyou.com"

  # customise the contents of the navbar at the top of the page.  The default
  # behaviour is to list all static pages not in the posts directory. When the
  # parameter below is set to true you will have to manually add entries to the
  # navbar, either by adding the following menu variable to the front matter of
  # the relevant pages
  #   menu = "navbar"
  # or by specifying menu entries in a similar way to the sidebar menu above.
  custom_navbar = true

  # show sharing icons on pages/posts (default: true)
  #sharingicons = true

  # Display post summaries instead of content in list templates (default: true)
  #truncate = true

  # Disable the use of sub-resource integrity on CSS/JS assets (default: false)
  # Useful if you're using a CDN or other host where you can't control cache headers
  #disable_sri = false

  # [params.sidebar]
    # Optional about block for sidebar (can be Markdown)
    # about = "A simple Hugo theme based on the [Bootstrap v4 blog example](http://v4-alpha.getbootstrap.com/examples/blog/)."

    # How many posts to show on the sidebar (Default: 5)
    # num_recent_posts = 5

  [params.social]
    # Optional, used for attribution in Twitter cards (ideally not a person
    # for example: nytimes, flickr, NatGeo, etc).
    # See: https://dev.twitter.com/cards/types/summary-large-image
    twitter = "username"

# Default content language for Hugo 0.17's multilingual support (default is "en")
# See: https://github.com/spf13/hugo/blob/master/docs/content/content/multilingual.md
#DefaultContentLanguage = "en"

# Languages to render
#[languages.en]
#[languages.bg]

# vim: ts=2 sw=2 et

